### ISSUE TITLE
Error Factory not initialized

### ISSUE THREAD

**Issue by silvadirceu** [k806house/sber-hp#1]
Hi @kisasexypantera94,
I'm trying to use covers80 to test the code in python, but I'm getting the following error:

Error preprocessing '/Users/dirceusilva/Documentos/BaseDados/covers32k/Toys_In_The_Attic/aerosmith+Toys_In_The_Attic+01-Toys_In_The_Attic.wav': You haven't initialized the factory yet... Please do it now!

What do I have to do?
Thanks for your code.

**Comment by kisasexypantera94** [comment]
Hi, maybe try removing this line
https://github.com/k806house/sber-hp/blob/57c0c910a5cbb76d8b67b7067b90c661b3621dc4/include/hpfw/spectrum/cqt.h#L33

**Comment by silvadirceu** [comment]
Thanks @kisasexypantera94,
it worked.
